### ISSUE TITLE
Not all metrics exported for 1.15.2

### ISSUE THREAD

**Issue by equals215** [Joshi425/minecraft-exporter#8]
Hi, not all my metrics are exported on my 1.15.2 server, for example I can't see the online players and use the Player Stats dashboard. 
Here is my /metrics dump:
```# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 98.0
python_gc_objects_collected_total{generation="1"} 257.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 4240.0
python_gc_collections_total{generation="1"} 385.0
python_gc_collections_total{generation="2"} 35.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="2",version="3.8.2"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.9622272e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.6920576e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.58896752382e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 19.169999999999998
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="Chlorouquine"} 100.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="Chlorouquine"} 7.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="Chlorouquine"} 14.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="Chlorouquine"} 15.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="Chlorouquine"} 100.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="Chlorouquine"} 237.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="iRony7"} 92.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="iRony7"} 7.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="iRony7"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="iRony7"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="iRony7"} 92.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="iRony7"} 344.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="froit16"} 780.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="froit16"} 14.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="froit16"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="froit16"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="froit16"} 780.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="froit16"} 218.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="Xyoh_"} 418.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="Xyoh_"} 17.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="Xyoh_"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="Xyoh_"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="Xyoh_"} 418.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="Xyoh_"} 184.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="h0rperr"} 708.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="h0rperr"} 22.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="h0rperr"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="h0rperr"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="h0rperr"} 708.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="h0rperr"} 202.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="Sluber11"} 66.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="Sluber11"} 5.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="Sluber11"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="Sluber11"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="Sluber11"} 66.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="Sluber11"} 112.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="SargasmX"} 906.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="SargasmX"} 17.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="SargasmX"} 6.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="SargasmX"} 15.600003242492676
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="SargasmX"} 906.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="SargasmX"} 340.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP blocks_mined_total Blocks a Player mined
# TYPE blocks_mined_total counter
# HELP blocks_picked_up_total Blocks a Player picked up
# TYPE blocks_picked_up_total counter
# HELP player_deaths_total How often a Player died
# TYPE player_deaths_total counter
# HELP player_jumps_total How often a Player has jumped
# TYPE player_jumps_total counter
# HELP cm_traveled_total How many cm a Player traveled, whatever that means
# TYPE cm_traveled_total counter
# HELP player_xp_total_total How much total XP a player has
# TYPE player_xp_total_total counter
player_xp_total{player="Pyronimbus"} 1043.0
# HELP player_current_level_total How much current XP a player has
# TYPE player_current_level_total counter
player_current_level{player="Pyronimbus"} 21.0
# HELP player_food_level_total How much food the player currently has
# TYPE player_food_level_total counter
player_food_level{player="Pyronimbus"} 20.0
# HELP player_health_total How much Health the player currently has
# TYPE player_health_total counter
player_health{player="Pyronimbus"} 20.0
# HELP player_score_total The Score of the player
# TYPE player_score_total counter
player_score{player="Pyronimbus"} 1043.0
# HELP entities_killed_total Entities killed by player
# TYPE entities_killed_total counter
# HELP damage_taken_total Damage Taken by Player
# TYPE damage_taken_total counter
# HELP damage_dealt_total Damage dealt by Player
# TYPE damage_dealt_total counter
# HELP blocks_crafted_total Items a Player crafted
# TYPE blocks_crafted_total counter
# HELP player_playtime_total Time in Minutes a Player was online
# TYPE player_playtime_total counter
# HELP player_advancements_total Number of completed advances of a player
# TYPE player_advancements_total counter
player_advancements{player="Pyronimbus"} 277.0
# HELP player_slept_total Times a Player slept in a bed
# TYPE player_slept_total counter
# HELP player_used_crafting_table_total Times a Player used a Crafting Table
# TYPE player_used_crafting_table_total counter
# HELP player_quests_finished_total Number of quests a Player has finished
# TYPE player_quests_finished_total counter
# HELP dim_tps_total TPS of a dimension
# TYPE dim_tps_total counter
# HELP dim_ticktime_total Time a Tick took in a Dimension
# TYPE dim_ticktime_total counter
# HELP overall_tps_total overall TPS
# TYPE overall_tps_total counter
overall_tps 20.0
# HELP overall_ticktime_total overall Ticktime
# TYPE overall_ticktime_total counter
overall_ticktime 11.972
# HELP player_online_total is 1 if player is online
# TYPE player_online_total counter
# HELP entities_total type and count of active entites
# TYPE entities_total counter
entities{entity="minecraft:pig"} 67.0
entities{entity="minecraft:item"} 66.0
entities{entity="minecraft:chicken"} 51.0
entities{entity="minecraft:sheep"} 39.0
entities{entity="minecraft:skeleton"} 29.0
entities{entity="minecraft:bat"} 23.0
entities{entity="minecraft:zombie"} 22.0
entities{entity="minecraft:creeper"} 19.0
entities{entity="minecraft:wolf"} 17.0
entities{entity="minecraft:cow"} 12.0
entities{entity="minecraft:salmon"} 11.0
entities{entity="minecraft:chest_minecart"} 9.0
entities{entity="minecraft:bee"} 7.0
entities{entity="minecraft:squid"} 5.0
entities{entity="minecraft:donkey"} 4.0
entities{entity="minecraft:horse"} 4.0
entities{entity="minecraft:spider"} 4.0
entities{entity="minecraft:rabbit"} 3.0
entities{entity="minecraft:trader_llama"} 2.0
entities{entity="minecraft:enderman"} 1.0
entities{entity="minecraft:iron_golem"} 1.0
entities{entity="minecraft:player"} 1.0
entities{entity="minecraft:wandering_trader"} 1.0```

**Comment by Joshi425** [comment]
I've just added proper 1.15 Support, please get the latest version with `docker pull joshi425/minecraft_exporter` and restart the exporter. Also online Players are only exported with RCON Enabled, so please make sure thats the case.

**Comment by equals215** [comment]
Just pulled the latest version of the docker image, turns out it got an error while launching :
```exporter_1    | RCON is enabled for server
exporter_1    | Traceback (most recent call last):
exporter_1    |   File "minecraft_exporter.py", line 298, in <module>
exporter_1    |     REGISTRY.register(MinecraftCollector())
exporter_1    |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 24, in register
exporter_1    |     names = self._get_names(collector)
exporter_1    |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 64, in _get_names
exporter_1    |     for metric in desc_func():
exporter_1    |   File "minecraft_exporter.py", line 287, in collect
exporter_1    |     for metric in self.update_metrics_for_player(player):
exporter_1    |   File "minecraft_exporter.py", line 246, in update_metrics_for_player
exporter_1    |     for entity, value in data["stats"]["minecraft:killed_by"].items():
exporter_1    | KeyError: 'minecraft:killed_by'

**Comment by Joshi425** [comment]
oh that was an oversight on my side, which happens when a Player wasn't killed by anything yet, I've just pushed a fix, please docker pull and restart again

**Comment by equals215** [comment]
Everything is fine except RCON is not working anymore, didn't changed my config just pulled the new image and regenerated my container with docker-compose.
There is a weird metric too, no one is connected to the server : 
```# HELP player_online_total is 1 if player is online
# TYPE player_online_total counter
player_online{player=""} 1.0

**Comment by equals215** [comment]
My server RCON is working, I have checked it with 3 different manners

**Comment by Joshi425** [comment]
mhm I've excluded emptystring as player, can you please try the latest version?

**Comment by equals215** [comment]
Still the same on my side, I carefully rm the container, pull and up the compose service

**Comment by equals215** [comment]
There is my server logs, you can see that exporter is connected but no RCON command is logged and a basic rcon test is working and logged in the server
```server_1      | [13:23:34] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
server_1      | [13:23:34] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
server_1      | [13:23:34] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
server_1      | [13:24:04] [RCON Listener #1/INFO]: Rcon connection from: exporter-container
server_1      | [13:41:45] [RCON Listener #1/INFO]: Rcon connection from: rcon-test
server_1      | [13:41:45] [Server thread/INFO]: [Rcon] Hello world

**Comment by equals215** [comment]
And here is my docker-compose : 
```version: '3.1'
services:
  exporter:
    image: 'joshi425/minecraft_exporter'
    environment:
      - RCON_HOST=server
      - RCON_PORT=25575
      - RCON_PASSWORD=password
    volumes:
      - /vanilla-plus/data/world:/world
    ports:
      - 8000:8000
    depends_on:
      - server
  prometheus:
    image: 'prom/prometheus'
    ports:
      - 9090:9090
    volumes:
      - /vanilla-plus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - exporter
  server:
    image: 'itzg/minecraft-server'
    environment:
      - MEMORY=4G
      - VERSION=1.15.2
      - FORGEVERSION=31.1.34
      - TYPE=FORGE
      - EULA=TRUE
      - FORCE_REDOWNLOAD=true
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - /vanilla-plus/data:/data

**Comment by equals215** [comment]
Well, after a short read of the code I realised that I didn't set FORGE_SERVER in my env, my bad.
Thanks for your time and this good exporter ;)

**Comment by equals215** [comment]
However, "player" is still shown when nobody is connected.
Here's a screenshot of my grafana dashboard 
<img width="158" alt="Capture d’écran 2020-05-12 à 16 19 14" src="https://user-images.githubusercontent.com/20166324/81703044-6039c900-946c-11ea-84ad-e95720880f0b.png">

**Comment by Joshi425** [comment]
sorry it took so long, it was an easy fix, please pull the latest version of the exporter and restart it
